version: "3.3"

services:
  db:
    image: postgres:14rc1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=botdb
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=postgres
    restart: always
  bot:
    image: kim368/tg_bot
    command: bash -c "
       chmod +x ./wait-postgres.sh
       ./wait-postgres.sh &&
       python manage.py migrate &&
       python manage.py bot"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
