# Generated by Django 3.2.7 on 2021-09-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('url', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Url')),
                ('name', models.TextField(null=True, verbose_name='Topic name')),
            ],
            options={
                'verbose_name': 'Topic',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('tg_id', models.PositiveIntegerField(help_text='Telegram chat id', primary_key=True, serialize=False, verbose_name='Person chatID')),
                ('name', models.TextField(help_text='Telegram person name', null=True, verbose_name='Person name')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('subscriptions', models.ManyToManyField(to='polls.Topics', verbose_name='Topic subscriptions')),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.CreateModel(
            name='Added_Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_to_subscribe', models.OneToOneField(help_text='Telegram chat id', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.topics', verbose_name='Person chatID')),
                ('profile', models.OneToOneField(help_text='Telegram chat id', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.profiles', verbose_name='Person chatID')),
            ],
            options={
                'verbose_name': 'Added subtopic',
                'ordering': ['profile'],
            },
        ),
    ]
