# Generated by Django 3.2.7 on 2021-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='subs',
            field=models.ManyToManyField(null=True, to='polls.Profiles', verbose_name='Topic subscriptions profiles'),
        ),
    ]
