# Generated by Django 3.2.7 on 2021-09-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topics_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added_subs',
            name='desire_to_subscribe',
            field=models.ForeignKey(help_text='Telegram chat id', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.topics', verbose_name='Person chatID'),
        ),
    ]
