# Generated by Django 3.2.7 on 2021-09-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_added_subs_desire_to_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='added_subs',
            name='desire_to_subscribe',
        ),
        migrations.CreateModel(
            name='Subs_Profile_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_to_subscribe', models.ForeignKey(help_text='desire_to_subscribe', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.topics', verbose_name='desire_to_subscribe')),
                ('profile', models.ForeignKey(help_text='Telegram profile', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.added_subs', verbose_name='Added_Subs')),
            ],
            options={
                'verbose_name': 'Added subtopic',
                'ordering': ['profile'],
            },
        ),
        migrations.AddField(
            model_name='added_subs',
            name='pr_topic_subs',
            field=models.OneToOneField(help_text='desire_to_subscribe', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.subs_profile_topic', verbose_name='desire_to_subscribe'),
        ),
    ]
