# Generated by Django 3.2.7 on 2021-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210921_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subs_profile_topic',
            options={'ordering': ['profile'], 'verbose_name': 'Subs_Profile_Topic'},
        ),
        migrations.RemoveField(
            model_name='added_subs',
            name='pr_topic_subs',
        ),
        migrations.AddField(
            model_name='added_subs',
            name='pr_topic_subs',
            field=models.ManyToManyField(help_text='pr_topic_subs', null=True, to='polls.Subs_Profile_Topic', verbose_name='pr_topic_subs'),
        ),
    ]
