# Generated by Django 3.2.7 on 2021-09-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210921_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Messages',
            fields=[
                ('profile', models.OneToOneField(help_text='Topic. Last news', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.profiles', verbose_name='Topic')),
                ('message_text', models.TextField(help_text='last message text', null=True, verbose_name='text')),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Last Message',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Last_News',
            fields=[
                ('url', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Url')),
                ('text', models.TextField(help_text='last news text', null=True, verbose_name='text')),
                ('date', models.DateTimeField(null=True, verbose_name='date')),
                ('topic', models.ManyToManyField(help_text='Topic. Last news', to='polls.Topics', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Last News',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_last_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.last_news', verbose_name='Topic Last News'),
        ),
    ]
