# Generated by Django 3.2.7 on 2021-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210922_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='last_news',
            options={'ordering': ['date'], 'verbose_name_plural': 'Last News'},
        ),
        migrations.AddField(
            model_name='last_news',
            name='is_sent_to_everyone',
            field=models.BooleanField(help_text='Has the news been sent to everyone?', null=True, verbose_name='is sent to everyone?'),
        ),
    ]
