# Generated by Django 3.2.7 on 2021-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210922_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topic_last_news',
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_last_news',
            field=models.ManyToManyField(null=True, to='polls.Last_News', verbose_name='Topic Last News'),
        ),
    ]
