# Generated by Django 3.2.7 on 2021-09-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210924_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['name'], 'verbose_name': 'Topic'},
        ),
        migrations.AddField(
            model_name='profiles',
            name='is_admin',
            field=models.BooleanField(help_text='is admin?', null=True, verbose_name='is admin?'),
        ),
    ]
